<?php

return [
    0 => [
        'id' => 0,
        'name' => '夸克网盘',
        'domain' => 'pan.quark.cn',
        'cookie_key' => 'quark_cookie',
        'pan_type' => 'quark',
        'url_pattern' => '/https:\/\/pan\.quark\.cn\/s\/[a-zA-Z0-9]+/',
        'class_name' => 'QuarkPan',
    ],
    1 => [
        'id' => 1,
        'name' => '阿里云盘',
        'domain' => ['www.alipan.com', 'www.aliyundrive.com'],
        'cookie_key' => 'alipan_cookie',
        'pan_type' => 'alipan',
        'url_pattern' => '/https:\/\/(www\.alipan\.com|www\.aliyundrive\.com)\/s\/[a-zA-Z0-9]+/',
        'class_name' => 'AlipanPan',
    ],
    2 => [
        'id' => 2,
        'name' => '百度网盘',
        'domain' => 'pan.baidu.com',
        'cookie_key' => 'baidu_cookie',
        'pan_type' => 'baidu',
        'url_pattern' => '/https:\/\/pan\.baidu\.com\/s\/[a-zA-Z0-9_-]+(\?pwd=[a-zA-Z0-9]+)?/',
        'class_name' => 'BaiduPan',
    ],
    3 => [
        'id' => 3,
        'name' => 'UC网盘',
        'domain' => ['drive.uc.cn', 'fast.uc.cn'],
        'cookie_key' => 'uc_cookie',
        'pan_type' => 'uc',
        'url_pattern' => '/https:\/\/drive\.uc\.cn\/s\/[a-zA-Z0-9]+/',
        'class_name' => 'UcPan',
    ],
    4 => [
        'id' => 4,
        'name' => '迅雷云盘',
        'domain' => 'pan.xunlei.com',
        'cookie_key' => 'xunlei_cookie',
        'pan_type' => 'xunlei',
        'url_pattern' => '/https:\/\/pan\.xunlei\.com\/s\/[a-zA-Z0-9_-]+(\?pwd=[a-zA-Z0-9]+)?/',
        'class_name' => 'XunleiPan',
    ],
    5 => [
        'id' => 5,
        'name' => '123网盘',
        'domain' => '123pan.com',
        'cookie_key' => 'pan123_cookie',
        'pan_type' => 'pan123',
        'url_pattern' => '/https:\/\/123\d{3}\.com\/s\/[a-zA-Z0-9-]+/',
        'class_name' => 'Pan123Pan',
    ],
    6 => [
        'id' => 6,
        'name' => '115网盘',
        'domain' => '115cdn.com',
        'cookie_key' => 'pan115_cookie',
        'pan_type' => 'pan115',
        'url_pattern' => '/https:\/\/115cdn\.com\/s\/[a-zA-Z0-9]+\?password=[a-zA-Z0-9]+/',
        'class_name' => 'Pan115Pan',
    ],
    7 => [
        'id' => 7,
        'name' => '天翼网盘',
        'domain' => 'cloud.189.cn',
        'cookie_key' => 'tianyi_cookie',
        'pan_type' => 'tianyi',
        'url_pattern' => '/https:\/\/cloud\.189\.cn\/t\/[a-zA-Z0-9]+/',
        'class_name' => 'TianyiPan',
    ],
    8 => [
        'id' => 8,
        'name' => '移动网盘',
        'domain' => 'caiyun.139.com',
        'cookie_key' => 'yidong_cookie',
        'pan_type' => 'yidong',
        'url_pattern' => '/https:\/\/caiyun\.139\.com\/m\/i\?[a-zA-Z0-9]+/',
        'class_name' => 'YidongPan',
    ],
    9 => [
        'id' => 9,
        'name' => '磁力链接',
        'domain' => '',
        'cookie_key' => '',
        'pan_type' => 'magnet',
        'url_pattern' => '/magnet:\?xt=urn:btih:[a-fA-F0-9]{40}(&[^&]+)*/',
        'class_name' => 'MagnetPan',
    ],
];
